/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_DoorLock_indicationSWC_Type.h
 * Generated on: Thu Mar 14 13:38:26 EET
 ********************************************************************/

#ifndef RTE_DOORLOCK_INDICATIONSWC_TYPE_H
#define RTE_DOORLOCK_INDICATIONSWC_TYPE_H


#include "Rte_Type.h"

#ifdef __cplusplus
	extern "C" {
#endif /* __cplusplus */

/*************************** range types *****************************/

#define my_uint8_LowerLimit  (0U)
#define my_uint8_UpperLimit (255U)

/************************ enumeration types **************************/



#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* RTE_DOORLOCK_INDICATIONSWC_TYPE_H */
