/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_DoorLock_indicationSWC.h
 * Generated on: Thu Mar 14 13:38:26 EET
 ********************************************************************/

#ifndef RTE_DOORLOCK_INDICATIONSWC_H
#define RTE_DOORLOCK_INDICATIONSWC_H

#include "Rte_DoorLock_indicationSWC_Type.h"

#ifdef __cplusplus
	extern "C" {
#endif /* __cplusplus */

/**************** component data structure definition ****************/

#ifndef IN_RTE_C
typedef const Rte_CDS_DoorLock_indicationSWC * const Rte_Instance;
#endif

/************************* instance handle ***************************/

extern const Rte_CDS_DoorLock_indicationSWC * const Rte_Inst_DoorLock_indicationSWC;

/************************ application errors *************************/

#define RTE_E_IF_CS_LED_E_OK ((Std_ReturnType)0)
#define RTE_E_IF_CS_LED_E_NOK ((Std_ReturnType)1)

/*************************** init values *****************************/


/****************** per instance memory definition *******************/


/************************* exclusive areas ***************************/


/************************* RTE API mapping ***************************/

/*****************************************************
 * Port: 		RP_SR_DoorState
 * Interface:	IF_SR_DoorLock
 * DataElement:	DoorState
 * Runnable:	DoorLock_Indication
 *****************************************************/
extern my_uint8 Rte_IRead_DoorLock_indicationSWC_DoorLock_Indication_RP_SR_DoorState_DoorState (void);
#ifndef IN_RTE_C
#define Rte_IRead_DoorLock_Indication_RP_SR_DoorState_DoorState() \
	Rte_IRead_DoorLock_indicationSWC_DoorLock_Indication_RP_SR_DoorState_DoorState()
#endif

/*****************************************************
 * Port: 		RP_CS_LedSwitch
 * Interface:	IF_CS_LED
 * Operation:	Led_Switch
 * Sync/Async:	Synchronous
 *****************************************************/
extern Std_ReturnType Rte_Call_DoorLock_indicationSWC_RP_CS_LedSwitch_Led_Switch (my_uint8 LedState);
#ifndef IN_RTE_C
#define Rte_Call_RP_CS_LedSwitch_Led_Switch(LedState) \
	Rte_Call_DoorLock_indicationSWC_RP_CS_LedSwitch_Led_Switch(LedState)
#endif


/**************** event triggered runnable entities *******************/

/*****************************************************
 * Runnable: 	DoorLock_Indication
 * Period:		0.012
 *****************************************************/
extern void DoorLock_Indcation_runnable(void);


/******** ARUnit-specific function pointers for server call delegates *********/
typedef Std_ReturnType (*FunctionPtr_DoorLock_indicationSWC_RP_CS_LedSwitch_Led_Switch)(my_uint8 LedState);


#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* RTE_DOORLOCK_INDICATIONSWC_H */
