/********************************************************************
 * Automatically generated by ARUnit
 * Filename: ARUnit_DoorLock_indicationSWC_.c
 * Generated on: Thu Mar 14 13:38:26 EET
 ********************************************************************/

#include "string.h"
#include "ARUnit_DoorLock_indicationSWC.h"


extern const Rte_CDS_DoorLock_indicationSWC Rte_Instance_DoorLock_indicationSWC;
extern const Rte_CDS_DoorLock_indicationSWC * const Rte_Inst_DoorLock_indicationSWC;


extern Std_ReturnType DoorLock_indicationSWC_RP_CS_LedSwitch_Led_Switch_Buffer_retcode;

extern FunctionPtr_DoorLock_indicationSWC_RP_CS_LedSwitch_Led_Switch Rte_Call_DoorLock_indicationSWC_RP_CS_LedSwitch_Led_Switch_Delegate;

DECLSPEC_EXPORT void ARUnit_IWrite_DoorLock_indicationSWC_DoorLock_Indication_RP_SR_DoorState_DoorState(my_uint8 DoorState)
{
	(Rte_Inst_DoorLock_indicationSWC)->DoorLock_Indication_RP_SR_DoorState_DoorState->value = DoorState;
}
DECLSPEC_EXPORT my_uint8* ARUnit_IWriteRef_DoorLock_indicationSWC_DoorLock_Indication_RP_SR_DoorState_DoorState(void)
{
	return &(Rte_Inst_DoorLock_indicationSWC)->DoorLock_Indication_RP_SR_DoorState_DoorState->value;
}
DECLSPEC_EXPORT my_uint8 ARUnit_IRead_DoorLock_indicationSWC_DoorLock_Indication_RP_SR_DoorState_DoorState(void)
{
	return (Rte_Inst_DoorLock_indicationSWC)->DoorLock_Indication_RP_SR_DoorState_DoorState->value;
}
DECLSPEC_EXPORT void ARUnit_Call_DoorLock_indicationSWC_RP_CS_LedSwitch_Led_Switch_ReturnCode(Std_ReturnType returnCode)
{
	DoorLock_indicationSWC_RP_CS_LedSwitch_Led_Switch_Buffer_retcode = returnCode;
}

DECLSPEC_EXPORT void ARUnit_Set_DoorLock_indicationSWC_RP_CS_LedSwitch_Led_Switch_Delegate(FunctionPtr_DoorLock_indicationSWC_RP_CS_LedSwitch_Led_Switch  delegate)
{
	Rte_Call_DoorLock_indicationSWC_RP_CS_LedSwitch_Led_Switch_Delegate = delegate;
}

DECLSPEC_EXPORT void ARUnit_Trigger_DoorLock_indicationSWC_DoorLock_Indcation_runnable(void)
{
	DoorLock_Indcation_runnable();
}
